LogLevel = "info"
Scanner.Schedule = "@every 30m"
TranscodingCacheSize = '150MiB'
MusicFolder = '/music'
DataFolder = '/data'
CacheFolder = '/data/cache'
Plugins.folder='/data/plugins'
Agents = 'apple-music,artist-nfo-metadata,deezer,lastfm,listenbrainz'
AutoTranscodeDownload = false
Backup.Path = '/backup'
Backup.Schedule = '@weekly'
Backup.Count = 2
CoverArtPriority = "embedded, cover.*, folder.*, front.*, external"
CoverArtQuality = '100'
DefaultDownsamplingFormat = 'mp3'
DefaultDownloadableShare = true
DefaultTheme = 'AMusic'
DiscArtPriority = "embedded, disc*.*, cd*.*, cover.*, folder.*, front.*, discsubtitle"
EnableArtworkUpload = false
EnableTranscodingCancellation = true
EnableTranscodingConfig = true
# FFmpegPath = /usr/sbin/ffmpeg
IgnoredArticles = "The"
LastFM.ApiKey = "9489f75080d65eeeb3b60a74ac14fbcd"
LastFM.Secret = "5f02b1afe06728072afcdfe50af412e6"
PasswordEncryptionKey = "fuckler"
PlaylistsPath = "/Playlists"
Plugins.Enabled = true
Plugins.AutoReload = true
Plugins.LogLevel = "info"
Scanner.WatcherWait = "20s"
Scanner.ArtistJoiner = ','
Scanner.PurgeMissing = "full"
SessionTimeout = "24h"
#ShareURL = "LOOK THIS UP IF YOU HOST"
Subsonic.ArtistParticipations = true
Subsonic.AppendAlbumVersion = false
Tags.arranger.Ignore = true
Tags.composter.Ignore = true
Tags.mixer.Ignore = true
Tags.engineer.Ignore = true
Tags.comment.Ignore = true
PID.Album = "album"
